#!/bin/sh
# If no configure script exists in the base directory, run this
# script to bootstrap the project via automake and autoconf
# OR
# If the configure.ac script has been edited, run this script to
# regenerate the configure script.
#
# If this script generates some warnings, run autoupdate on the
# configure.ac file.
#
if test -f "/usr/local/bin/autoconf"; then
   export ACLOCAL="/usr/local/bin/aclocal"
   export AUTOHEADER="/usr/local/bin/autoheader"
   export AUTOCONF="/usr/local/bin/autoconf"
   export AUTOMAKE="/usr/local/bin/automake"
else
   export ACLOCAL="aclocal"
   export AUTOHEADER="autoheader"
   export AUTOCONF="autoconf"
   export AUTOMAKE="automake"
fi

echo "+ collecting m4 macros"
${ACLOCAL} -I config \
|| { echo "ERROR: aclocal failed"; exit 1; }

echo "+ generating configuration header"
${AUTOHEADER} --warnings=all \
|| { echo "ERROR: autoheader failed"; exit 1; }

echo "+ generating makefile inputs"
${AUTOMAKE} --warnings=all --foreign --include-deps \
|| { echo "ERROR: automake failed"; exit 1; }

echo "+ generating configure script"
${AUTOCONF} --warnings=all \
|| { echo "ERROR: autoconf failed"; exit 1; }

echo "BOOTSTRAP COMPLETE"


##-- END OF SCRIPT --##