# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.search.defaultengine", "engine:///usr/lib/mozilla-seamonkey-1.0.9/searchplugins/google.src");
user_pref("browser.startup.homepage_override.mstone", "rv:1.8.0.14eol");
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("prefs.converted-to-utf8", true);
user_pref("signon.SignonFileName", "82593309.s");
